/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package notasponderadas;

import java.text.DecimalFormat;

/**
 *
 * @author Emerson
 */
public class GUI_NotasPonderadas extends javax.swing.JFrame {

    /**
     * Creates new form GUI_NotasPonderadas
     */
    public GUI_NotasPonderadas() {
        initComponents();
        jtf_Nota3.setEnabled(false);
        jtf_Peso3.setEnabled(false);
        jtf_Nota4.setEnabled(false);
        jtf_Peso4.setEnabled(false);
        jtf_Nota5.setEnabled(false);
        jtf_Peso5.setEnabled(false);
        
        CheckBox_Nota4.setEnabled(false);
        CheckBox_Nota5.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtf_Nota1 = new javax.swing.JTextField();
        jtf_Nota2 = new javax.swing.JTextField();
        jtf_Nota3 = new javax.swing.JTextField();
        jtf_Nota4 = new javax.swing.JTextField();
        jtf_Nota5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CheckBox_Nota1 = new javax.swing.JCheckBox();
        CheckBox_Nota2 = new javax.swing.JCheckBox();
        CheckBox_Nota3 = new javax.swing.JCheckBox();
        CheckBox_Nota4 = new javax.swing.JCheckBox();
        CheckBox_Nota5 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtf_Peso1 = new javax.swing.JTextField();
        jtf_Peso2 = new javax.swing.JTextField();
        jtf_Peso3 = new javax.swing.JTextField();
        jtf_Peso4 = new javax.swing.JTextField();
        jtf_Peso5 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jb_HabilitarPesos = new javax.swing.JButton();
        jb_VerificarPesos = new javax.swing.JButton();
        jb_Calcular = new javax.swing.JButton();
        jb_Limpar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtf_MediaNota = new javax.swing.JTextField();
        jtf_TotalDosPesos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de Notas Ponderadas");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Emerson Moreno de Oliveira");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("RA: 16498.98 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Notas");

        jtf_Nota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Nota4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_Nota1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_Nota2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_Nota3, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_Nota4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_Nota5))))
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtf_Nota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Nota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Nota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Nota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Nota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Habilitado");

        CheckBox_Nota1.setSelected(true);
        CheckBox_Nota1.setText("Nota 1");
        CheckBox_Nota1.setEnabled(false);

        CheckBox_Nota2.setSelected(true);
        CheckBox_Nota2.setText("Nota 2");
        CheckBox_Nota2.setEnabled(false);

        CheckBox_Nota3.setText("Nota 3");
        CheckBox_Nota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_Nota3ActionPerformed(evt);
            }
        });

        CheckBox_Nota4.setText("Nota 4");
        CheckBox_Nota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_Nota4ActionPerformed(evt);
            }
        });

        CheckBox_Nota5.setText("Nota 5");
        CheckBox_Nota5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_Nota5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CheckBox_Nota1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CheckBox_Nota2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CheckBox_Nota3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CheckBox_Nota4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CheckBox_Nota5)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(CheckBox_Nota1)
                .addGap(18, 18, 18)
                .addComponent(CheckBox_Nota2)
                .addGap(18, 18, 18)
                .addComponent(CheckBox_Nota3)
                .addGap(18, 18, 18)
                .addComponent(CheckBox_Nota4)
                .addGap(18, 18, 18)
                .addComponent(CheckBox_Nota5)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setText("Pesos");

        jtf_Peso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Peso2ActionPerformed(evt);
            }
        });

        jtf_Peso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Peso4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_Peso5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_Peso4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_Peso3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_Peso2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jLabel6))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jtf_Peso1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jtf_Peso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Peso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Peso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Peso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Peso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jb_HabilitarPesos.setBackground(new java.awt.Color(153, 204, 255));
        jb_HabilitarPesos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_HabilitarPesos.setForeground(new java.awt.Color(255, 255, 255));
        jb_HabilitarPesos.setText("DESABILITAR MÉDIA COM PESOS");
        jb_HabilitarPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_HabilitarPesosActionPerformed(evt);
            }
        });

        jb_VerificarPesos.setBackground(new java.awt.Color(153, 153, 255));
        jb_VerificarPesos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_VerificarPesos.setText("VERIFICAR PESOS");
        jb_VerificarPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_VerificarPesosActionPerformed(evt);
            }
        });

        jb_Calcular.setBackground(new java.awt.Color(0, 204, 153));
        jb_Calcular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_Calcular.setForeground(new java.awt.Color(255, 255, 255));
        jb_Calcular.setText("CALCULAR");
        jb_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_CalcularActionPerformed(evt);
            }
        });

        jb_Limpar.setBackground(new java.awt.Color(0, 204, 204));
        jb_Limpar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_Limpar.setText("LIMPAR");
        jb_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_HabilitarPesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_VerificarPesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Calcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jb_HabilitarPesos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_VerificarPesos)
                .addGap(73, 73, 73)
                .addComponent(jb_Calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_Limpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setText("Média = ");

        jtf_TotalDosPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_TotalDosPesosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jtf_MediaNota, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jtf_TotalDosPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_MediaNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_TotalDosPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_Nota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Nota4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Nota4ActionPerformed

    private void jtf_Peso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Peso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Peso2ActionPerformed

    private void jtf_Peso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Peso4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Peso4ActionPerformed

    private void jtf_TotalDosPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_TotalDosPesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_TotalDosPesosActionPerformed

    private void CheckBox_Nota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_Nota3ActionPerformed
        
        if (CheckBox_Nota3.isSelected()) {
        jtf_Nota3.setEnabled(true);
        if (calcularNotasPoderadas.isCalculoTemPeso()){
            
       
        jtf_Peso3.setEnabled(true);
         }
        CheckBox_Nota4.setEnabled(true);
            
        }else {
        jtf_Nota3.setEnabled(false);
        jtf_Peso3.setEnabled(false);
        CheckBox_Nota4.setEnabled(false);
        CheckBox_Nota4.setSelected(false);
        jtf_Nota4.setEnabled(false);
        jtf_Peso4.setEnabled(false);
        CheckBox_Nota5.setEnabled(false);
        CheckBox_Nota5.setSelected(false);
        jtf_Nota5.setEnabled(false);
        jtf_Peso5.setEnabled(false);
         jtf_Nota3.setText("");
         jtf_Nota4.setText("");
         jtf_Nota5.setText("");
         jtf_Peso3.setText("");
         jtf_Peso4.setText("");
         jtf_Peso5.setText("");
        }
    }//GEN-LAST:event_CheckBox_Nota3ActionPerformed

    private void CheckBox_Nota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_Nota4ActionPerformed
        
        if (CheckBox_Nota4.isSelected()) {
        jtf_Nota4.setEnabled(true);
        if (calcularNotasPoderadas.isCalculoTemPeso()){
        jtf_Peso4.setEnabled(true);
        }
        CheckBox_Nota5.setEnabled(true);
            
        }else {
        jtf_Nota4.setEnabled(false);
        jtf_Peso4.setEnabled(false);
        CheckBox_Nota5.setEnabled(false);
        CheckBox_Nota5.setSelected(false);
        jtf_Nota5.setEnabled(false);
        jtf_Peso5.setEnabled(false);
         jtf_Nota4.setText("");
         jtf_Nota5.setText("");
         jtf_Peso4.setText("");
         jtf_Peso5.setText("");
        }
    }//GEN-LAST:event_CheckBox_Nota4ActionPerformed

    private void CheckBox_Nota5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_Nota5ActionPerformed
        
         if (CheckBox_Nota5.isSelected()) {
        jtf_Nota5.setEnabled(true);
        if (calcularNotasPoderadas.isCalculoTemPeso()){
        jtf_Peso5.setEnabled(true);
        }
            
        }else {
        jtf_Nota5.setEnabled(false);
        jtf_Peso5.setEnabled(false);
        
         jtf_Nota5.setText("");
         jtf_Peso5.setText("");
        }
    }//GEN-LAST:event_CheckBox_Nota5ActionPerformed

    private void jb_HabilitarPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_HabilitarPesosActionPerformed
        
        if(calcularNotasPoderadas.isCalculoTemPeso()){
            calcularNotasPoderadas.setCalculoTemPeso(false);
            jb_HabilitarPesos.setText("HABILITAR MÉDIA COM PESOS");
            jtf_Peso1.setEnabled(false);
            jtf_Peso2.setEnabled(false);
            jtf_Peso3.setEnabled(false);
            jtf_Peso4.setEnabled(false);
            jtf_Peso5.setEnabled(false);
             } else {
            calcularNotasPoderadas.setCalculoTemPeso(true);
            jb_HabilitarPesos.setText("DESABILITAR MÉDIA COM PESOS");
            jtf_Peso1.setEnabled(true);
            jtf_Peso2.setEnabled(true);
            if (CheckBox_Nota3.isSelected()) {
                jtf_Peso3.setEnabled(true);
            }
            if (CheckBox_Nota4.isSelected()) {
                jtf_Peso4.setEnabled(true);
            }
            if (CheckBox_Nota5.isSelected()) {
                jtf_Peso5.setEnabled(true);
            }
            
        }
    }//GEN-LAST:event_jb_HabilitarPesosActionPerformed

    private void jb_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_LimparActionPerformed
        jtf_Nota1.setText("");
        jtf_Nota2.setText(""); 
        jtf_Nota3.setText("");
         jtf_Nota4.setText("");
         jtf_Nota5.setText("");
         jtf_Peso1.setText("");
         jtf_Peso2.setText("");
         jtf_Peso3.setText("");
         jtf_Peso4.setText("");
         jtf_Peso5.setText("");
         
         
         jtf_Nota1.setEnabled(true);
         jtf_Peso1.setEnabled(true);
         jtf_Nota2.setEnabled(true);
         jtf_Peso2.setEnabled(true);
         jtf_Nota3.setEnabled(false);
         jtf_Peso3.setEnabled(false);
         jtf_Nota4.setEnabled(false);
         jtf_Peso4.setEnabled(false);
         jtf_Nota5.setEnabled(false);
         jtf_Peso5.setEnabled(false);

         
         
         jtf_MediaNota.setText("");
         jtf_TotalDosPesos.setText("");
         
         calcularNotasPoderadas.limpar();
          calcularNotasPoderadas.setCalculoTemPeso(true);
          jb_HabilitarPesos.setText("DESABILITAR MÉDIA COM PESOS");
         
    }//GEN-LAST:event_jb_LimparActionPerformed

    private void jb_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_CalcularActionPerformed
        calcularNotasPoderadas.setNota1(Double.parseDouble(jtf_Nota1.getText()));
        calcularNotasPoderadas.setNota2(Double.parseDouble(jtf_Nota2.getText()));

       // calcularNotasPoderadas.setPeso1(Double.parseDouble(jtf_Peso1.getText()));
       // calcularNotasPoderadas.setPeso2(Double.parseDouble(jtf_Peso2.getText()));
        
        if (CheckBox_Nota3.isSelected()) {
calcularNotasPoderadas.setNota3(Double.parseDouble(jtf_Nota3.getText()));
}
if (CheckBox_Nota4.isSelected()) {
calcularNotasPoderadas.setNota4(Double.parseDouble(jtf_Nota4.getText()));
}
if (CheckBox_Nota5.isSelected()) {
calcularNotasPoderadas.setNota5(Double.parseDouble(jtf_Nota5.getText()));
}
if (calcularNotasPoderadas.isCalculoTemPeso()) {
calcularNotasPoderadas.setPeso1(Double.parseDouble(jtf_Peso1.getText()));
calcularNotasPoderadas.setPeso2(Double.parseDouble(jtf_Peso2.getText()));
if (CheckBox_Nota3.isSelected()) {
calcularNotasPoderadas.setPeso3(Double.parseDouble(jtf_Peso3.getText()));
}
if (CheckBox_Nota4.isSelected()) {
calcularNotasPoderadas.setPeso4(Double.parseDouble(jtf_Peso4.getText()));
}
if (CheckBox_Nota5.isSelected()) {
calcularNotasPoderadas.setPeso5(Double.parseDouble(jtf_Peso5.getText()));
}

}        
        
        calcularNotasPoderadas.calcularAMedia();
        
         jtf_MediaNota.setText(df.format(calcularNotasPoderadas.getMediaFinal()));
         
         jtf_TotalDosPesos.setText(String.valueOf(calcularNotasPoderadas.getTotalDosPesos()));

    }//GEN-LAST:event_jb_CalcularActionPerformed

    private void jb_VerificarPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_VerificarPesosActionPerformed
        if (calcularNotasPoderadas.isCalculoTemPeso()){
            
    calcularNotasPoderadas.setTotalDosPesos(
Double.parseDouble(jtf_Peso1.getText()) +
Double.parseDouble(jtf_Peso2.getText()) +
Double.parseDouble(jtf_Peso3.getText()) +
Double.parseDouble(jtf_Peso4.getText()) +
Double.parseDouble(jtf_Peso5.getText()));

jtf_TotalDosPesos.setText(String.valueOf(
calcularNotasPoderadas.getTotalDosPesos()));

} else {
calcularNotasPoderadas.setTotalDosPesos(0);
jtf_TotalDosPesos.setText("");
}
    }//GEN-LAST:event_jb_VerificarPesosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_NotasPonderadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_NotasPonderadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_NotasPonderadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_NotasPonderadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_NotasPonderadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox_Nota1;
    private javax.swing.JCheckBox CheckBox_Nota2;
    private javax.swing.JCheckBox CheckBox_Nota3;
    private javax.swing.JCheckBox CheckBox_Nota4;
    private javax.swing.JCheckBox CheckBox_Nota5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jb_Calcular;
    private javax.swing.JButton jb_HabilitarPesos;
    private javax.swing.JButton jb_Limpar;
    private javax.swing.JButton jb_VerificarPesos;
    private javax.swing.JTextField jtf_MediaNota;
    private javax.swing.JTextField jtf_Nota1;
    private javax.swing.JTextField jtf_Nota2;
    private javax.swing.JTextField jtf_Nota3;
    private javax.swing.JTextField jtf_Nota4;
    private javax.swing.JTextField jtf_Nota5;
    private javax.swing.JTextField jtf_Peso1;
    private javax.swing.JTextField jtf_Peso2;
    private javax.swing.JTextField jtf_Peso3;
    private javax.swing.JTextField jtf_Peso4;
    private javax.swing.JTextField jtf_Peso5;
    private javax.swing.JTextField jtf_TotalDosPesos;
    // End of variables declaration//GEN-END:variables
Calcular_NotasPoderadas calcularNotasPoderadas = new
        Calcular_NotasPoderadas ();
DecimalFormat df = new DecimalFormat("##.##");
}
