/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoPizzaria.view;

import ProjetoPizzaria.DAO.UsuariosDAO;
import ProjetoPizzaria.modelo.Usuarios;
import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import java.awt.Toolkit;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import jdk.nashorn.internal.ir.BreakNode;

/**
 *
 * @author Casa
 */
public class FrmLogin extends javax.swing.JFrame {

    Boolean verifica = false;
    public String login;
    String Senha;

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoDeBotao1 = new javax.swing.ButtonGroup();
        BtnLogin = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        RbFuncionario = new javax.swing.JRadioButton();
        RbGerente = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Realize seu Login");
        setMinimumSize(new java.awt.Dimension(634, 480));
        setPreferredSize(new java.awt.Dimension(621, 485));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnLogin.setText("Login");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 407, 78, -1));
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 265, 230, -1));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 230, -1));

        RbFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        GrupoDeBotao1.add(RbFuncionario);
        RbFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RbFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        RbFuncionario.setText("Funcionário");
        RbFuncionario.setOpaque(false);
        RbFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(RbFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        RbGerente.setBackground(new java.awt.Color(255, 255, 255));
        GrupoDeBotao1.add(RbGerente);
        RbGerente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RbGerente.setForeground(new java.awt.Color(255, 255, 255));
        RbGerente.setText("Gerente");
        RbGerente.setOpaque(false);
        RbGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbGerenteActionPerformed(evt);
            }
        });
        getContentPane().add(RbGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Confirme seus dados e Realize o ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjetoImagem/login.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 680, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        if (verifica) {
            login = txtLogin.getText().toString();

            Usuarios user = new Usuarios();
            UsuariosDAO userDao = new UsuariosDAO();
            if (RbGerente.isSelected()) {
                try {
                    userDao.VerificarLoginGerente(user, login);

                    Senha = user.getSenha().toString();
                                   } catch (Exception e) {
                }

                if (txtSenha.getText().equals(Senha)) {
                    JOptionPane.showMessageDialog(null, "Login Efetuado com Sucesso");
                    this.dispose();
                    new  FrmPrincipal().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Login ou Senha Incorretos");
                    txtSenha.setText("");
                    txtSenha.requestFocus();
                     this.dispose();
                    new  FrmPrincipal().setVisible(true);
                }
            }
            if (RbFuncionario.isSelected()) {
                try {
                    userDao.VerificarLoginFuncionario(user, login);

                    Senha = user.getSenha().toString();
                                   } catch (Exception e) {

                }

                if (txtSenha.getText().equals(Senha)) {
                    JOptionPane.showMessageDialog(null, "Login Efetuado com Sucesso");
                    this.dispose();
                    new  FrmPrincipal().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Login ou Senha Incorretos");
                    txtSenha.setText("");
                    txtSenha.requestFocus();
                }
            }
        } else {
JOptionPane.showMessageDialog(null, "Por favor selecione algum cargo");
        }
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void RbFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbFuncionarioActionPerformed
        verifica = true;    }//GEN-LAST:event_RbFuncionarioActionPerformed

    private void RbGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbGerenteActionPerformed
        verifica = true;        // TODO add your handling code here:
    }//GEN-LAST:event_RbGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            Properties props = new Properties();
            
            props.put("logoString", "Pizzaapp"); 
            props.put("licenseKey", "INSERT YOUR LICENSE KEY HERE");
            
            props.put("selectionBackgroundColor", "180 240 197"); 
            props.put("menuSelectionBackgroundColor", "168 168 168"); 
            
            props.put("controlColor", "218 254 230");
            props.put("controlColorLight", "218 254 230");
            props.put("controlColorDark", "180 240 197"); 

            props.put("buttonColor", "255 0 0");
            props.put("buttonColorLight", "255 0 0");
            props.put("buttonColorDark", "255 0 0");

            props.put("rolloverColor", "50 205 50"); 
            props.put("rolloverColorLight", "50 205 50"); 
            props.put("rolloverColorDark", "50 205 50"); 

            props.put("windowTitleForegroundColor", "0 0 0");
            props.put("windowTitleBackgroundColor", "255 255 255"); 
            props.put("windowTitleColorLight", "217 217 217"); 
            props.put("windowTitleColorDark", "179 179 179"); 
            props.put("windowBorderColor", "255 255 255");
            
            // set your theme
            McWinLookAndFeel.setCurrentTheme(props);
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            new FrmLogin();
        } catch (Exception e) {
            
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.ButtonGroup GrupoDeBotao1;
    private javax.swing.JRadioButton RbFuncionario;
    private javax.swing.JRadioButton RbGerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("pizza.png")));
    }
}
