/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoPizzaria.view;

import java.awt.Toolkit;

/**
 *
 * @author Casa
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {     
        initComponents();
        setIcon();
       // setExtendedState(FrmPrincipal.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuGerenciarIngrediente = new javax.swing.JMenu();
        MenuRegistrarNovoIngrediente = new javax.swing.JMenuItem();
        MenuDeletarAlterar = new javax.swing.JMenuItem();
        MenuAtualizarIngredientes = new javax.swing.JMenuItem();
        MenuPesquisarIngrediente = new javax.swing.JMenuItem();
        MenuGerenciarBordas = new javax.swing.JMenu();
        MenuCadastrarSabor = new javax.swing.JMenuItem();
        MenuAltDelBordas = new javax.swing.JMenuItem();
        MenuPesquisarBordas = new javax.swing.JMenuItem();
        Sabores = new javax.swing.JMenu();
        MenuGerenciarSabores = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjetoImagem/LOGO.png"))); // NOI18N

        desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );

        MenuGerenciarIngrediente.setText("Gerenciar Ingredientes");

        MenuRegistrarNovoIngrediente.setText("Registrar Novo Ingrediente");
        MenuRegistrarNovoIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarNovoIngredienteActionPerformed(evt);
            }
        });
        MenuGerenciarIngrediente.add(MenuRegistrarNovoIngrediente);

        MenuDeletarAlterar.setText("Alterar / Deletar Ingredientes");
        MenuDeletarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeletarAlterarActionPerformed(evt);
            }
        });
        MenuGerenciarIngrediente.add(MenuDeletarAlterar);

        MenuAtualizarIngredientes.setText("Atualizar Estoque de Ingredientes");
        MenuAtualizarIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAtualizarIngredientesActionPerformed(evt);
            }
        });
        MenuGerenciarIngrediente.add(MenuAtualizarIngredientes);

        MenuPesquisarIngrediente.setText("Pesquisar Ingredientes");
        MenuPesquisarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPesquisarIngredienteActionPerformed(evt);
            }
        });
        MenuGerenciarIngrediente.add(MenuPesquisarIngrediente);

        jMenuBar1.add(MenuGerenciarIngrediente);

        MenuGerenciarBordas.setText("Gerenciar Bordas");

        MenuCadastrarSabor.setText("Cadastrar Sabor");
        MenuCadastrarSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarSaborActionPerformed(evt);
            }
        });
        MenuGerenciarBordas.add(MenuCadastrarSabor);

        MenuAltDelBordas.setText("Alterar / Deletar Bordas");
        MenuAltDelBordas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAltDelBordasActionPerformed(evt);
            }
        });
        MenuGerenciarBordas.add(MenuAltDelBordas);

        MenuPesquisarBordas.setText("Pesquisar Bordas");
        MenuPesquisarBordas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPesquisarBordasActionPerformed(evt);
            }
        });
        MenuGerenciarBordas.add(MenuPesquisarBordas);

        jMenuBar1.add(MenuGerenciarBordas);

        Sabores.setText("Gerenciar Pizzas");

        MenuGerenciarSabores.setText("Gerenciar Sabores");
        MenuGerenciarSabores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGerenciarSaboresActionPerformed(evt);
            }
        });
        Sabores.add(MenuGerenciarSabores);

        jMenuItem1.setText("Cadastrar Pizza");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Sabores.add(jMenuItem1);

        jMenuBar1.add(Sabores);

        jMenu1.setText("Outros Produtos");

        jMenuItem2.setText("Cadastrar Produtos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Alterar / Deletar Outros Produtos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Atualizar estoque");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem4.setText("Pesquisar Produtos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   

    }//GEN-LAST:event_formWindowOpened

    private void MenuRegistrarNovoIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarNovoIngredienteActionPerformed
      IFrmCadIngredientePizza ifrming = new IFrmCadIngredientePizza();
      desktop.add(ifrming);
      ifrming.show();
    }//GEN-LAST:event_MenuRegistrarNovoIngredienteActionPerformed

    private void MenuCadastrarSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarSaborActionPerformed
       IFrmCadSaborBorda ifrmcdb = new IFrmCadSaborBorda();
       desktop.add(ifrmcdb);
       ifrmcdb.show();
    }//GEN-LAST:event_MenuCadastrarSaborActionPerformed

    private void MenuAltDelBordasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAltDelBordasActionPerformed
IFrmGerenciaSaborBordas ifrmdsb = new IFrmGerenciaSaborBordas();
desktop.add(ifrmdsb);
ifrmdsb.show();
    }//GEN-LAST:event_MenuAltDelBordasActionPerformed

    private void MenuDeletarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeletarAlterarActionPerformed
IFrmGerenciaIngredientesPizza obj = new IFrmGerenciaIngredientesPizza();
desktop.add(obj);
obj.show();
    }//GEN-LAST:event_MenuDeletarAlterarActionPerformed

    private void MenuAtualizarIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAtualizarIngredientesActionPerformed
IFrmAtualizarEstoqueIngredientes obj = new IFrmAtualizarEstoqueIngredientes();
desktop.add(obj);
obj.show();
    }//GEN-LAST:event_MenuAtualizarIngredientesActionPerformed

    private void MenuPesquisarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPesquisarIngredienteActionPerformed
IFrmPesquisarIngrediente obj = new IFrmPesquisarIngrediente();
desktop.add(obj);
obj.show();

    }//GEN-LAST:event_MenuPesquisarIngredienteActionPerformed

    private void MenuPesquisarBordasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPesquisarBordasActionPerformed
IFrmPesquisarBordas obj = new IFrmPesquisarBordas();
desktop.add(obj);
obj.show();

    }//GEN-LAST:event_MenuPesquisarBordasActionPerformed

    private void MenuGerenciarSaboresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGerenciarSaboresActionPerformed
IFrmGerenciarSabores obj = new IFrmGerenciarSabores();
desktop.add(obj);
obj.show();

    }//GEN-LAST:event_MenuGerenciarSaboresActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
IFrmCadPizzas obj = new IFrmCadPizzas();
desktop.add(obj);
obj.show();


        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
IFrmCadOutrosProdutos obj = new IFrmCadOutrosProdutos();
desktop.add(obj);
obj.show();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
IFrmGerenciarOutrosProdutos obj = new IFrmGerenciarOutrosProdutos();
desktop.add(obj);
obj.show();


        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
IFrmPesquisarOutrosProdutos obj = new IFrmPesquisarOutrosProdutos();
desktop.add(obj);
obj.show();

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
IFrmAtualizarEstoqueProdutos obj = new IFrmAtualizarEstoqueProdutos();
desktop.add(obj);
obj.show();


        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("pizza.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAltDelBordas;
    private javax.swing.JMenuItem MenuAtualizarIngredientes;
    private javax.swing.JMenuItem MenuCadastrarSabor;
    private javax.swing.JMenuItem MenuDeletarAlterar;
    private javax.swing.JMenu MenuGerenciarBordas;
    private javax.swing.JMenu MenuGerenciarIngrediente;
    private javax.swing.JMenuItem MenuGerenciarSabores;
    private javax.swing.JMenuItem MenuPesquisarBordas;
    private javax.swing.JMenuItem MenuPesquisarIngrediente;
    private javax.swing.JMenuItem MenuRegistrarNovoIngrediente;
    private javax.swing.JMenu Sabores;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
