/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoPizzaria.view;

import ProjetoPizzaria.DAO.SaborBordaRecheadaDAO;
import ProjetoPizzaria.modelo.SaborBordaRecheada;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Casa
 */
public class IFrmCadSaborBorda extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmCadSaborBorda
     */
    public IFrmCadSaborBorda() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSaborBorda = new javax.swing.JTextField();
        BtnConfirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastrar Sabor da Borda");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Sabor da Borda");

        BtnConfirmar.setBackground(new java.awt.Color(255, 51, 51));
        BtnConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmar.setText("Cadastrar");
        BtnConfirmar.setToolTipText("");
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Preço:");

        jLabel3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtSaborBorda))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(BtnConfirmar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSaborBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(BtnConfirmar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed
        if (txtPreco.getText().equals("") && txtSaborBorda.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha os campos", "Preencher os campos", JOptionPane.OK_OPTION);
        } else if (txtPreco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, insira o preço", "Preencher preço", JOptionPane.OK_OPTION);
        } else if (txtSaborBorda.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, insira o sabor da borda", "Preencher sabor", JOptionPane.OK_OPTION);
        } else {
            try {
                double x = Double.parseDouble(txtPreco.getText());
                if (x <= 0) {
                    JOptionPane.showMessageDialog(null, "Por favor, preencha o campo preço corretamente", "Preenche preço", JOptionPane.OK_OPTION);
                    txtPreco.setText("");
                    txtPreco.requestFocus();
                } else {
                    int r = JOptionPane.showConfirmDialog(null, "Deseja realmente cadastrar essa borda?", "Cadastrar Bordas", JOptionPane.OK_OPTION);

                    if (r == 0) {

                        SaborBordaRecheada sbr = new SaborBordaRecheada();
                        sbr.setNomeSabor(txtSaborBorda.getText());
                        sbr.setValor(Double.parseDouble(txtPreco.getText()));
                        SaborBordaRecheadaDAO dao = new SaborBordaRecheadaDAO();
                        dao.AdicionarSaborBorda(sbr);
                        JOptionPane.showMessageDialog(null, "Borda Cadastrada com Sucesso");
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Por favor, preencha o campo preço corretamente", "Preenche preço", JOptionPane.OK_OPTION);
                txtPreco.setText("");
                txtPreco.requestFocus();
            }

        }
    }//GEN-LAST:event_BtnConfirmarActionPerformed

    private void jLabel3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel3AncestorAdded
        ImageIcon icon = new ImageIcon("src/ProjetoImagem/padrão.png");
    jLabel3.setIcon(new ImageIcon(icon.getImage().getScaledInstance(jLabel3.getWidth(),jLabel3.getHeight(), icon.getIconWidth()))); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3AncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtSaborBorda;
    // End of variables declaration//GEN-END:variables
}
