/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MenuSDI;

import javax.swing.ImageIcon;

/**
 *
 * @author lab
 */
public class DFrmQuebraCabeca extends javax.swing.JFrame {
boolean t1,t2,t3,t4;

    /**
     * Creates new form DFrmQuebraCabeca
     */
    public DFrmQuebraCabeca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbltr1 = new javax.swing.JLabel();
        lbltr2 = new javax.swing.JLabel();
        lbltr3 = new javax.swing.JLabel();
        lbltr4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/t1.jpg"))); // NOI18N
        lbl1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl1MouseDragged(evt);
            }
        });
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/t3.jpg"))); // NOI18N
        lbl2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl2MouseDragged(evt);
            }
        });
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/t4.jpg"))); // NOI18N
        lbl3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl3MouseDragged(evt);
            }
        });
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 220, 240));

        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/t2.jpg"))); // NOI18N
        lbl4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl4MouseDragged(evt);
            }
        });
        getContentPane().add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        lbltr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/costas.jpg"))); // NOI18N
        lbltr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltr1MouseEntered(evt);
            }
        });
        getContentPane().add(lbltr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        lbltr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/costas.jpg"))); // NOI18N
        lbltr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltr2MouseEntered(evt);
            }
        });
        getContentPane().add(lbltr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        lbltr3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/costas.jpg"))); // NOI18N
        lbltr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltr3MouseEntered(evt);
            }
        });
        getContentPane().add(lbltr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        lbltr4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/costas.jpg"))); // NOI18N
        lbltr4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltr4MouseEntered(evt);
            }
        });
        getContentPane().add(lbltr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseDragged
lbl1.setLocation(lbl1.getX() + evt.getX(), lbl1.getY() + evt.getY());
       t1 = true;
// TODO add your handling code here:
    }//GEN-LAST:event_lbl1MouseDragged

    private void lbl2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseDragged
    lbl2.setLocation(lbl2.getX() + evt.getX(), lbl2.getY() + evt.getY());
       t2 = true;
        

// TODO add your handling code here:
    }//GEN-LAST:event_lbl2MouseDragged

    private void lbl3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl3MouseDragged
lbl3.setLocation(lbl3.getX() + evt.getX(), lbl3.getY() + evt.getY());
       t3 = true;
        


// TODO add your handling code here:
    }//GEN-LAST:event_lbl3MouseDragged

    private void lbl4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl4MouseDragged
lbl4.setLocation(lbl4.getX() + evt.getX(), lbl4.getY() + evt.getY());
       t4 = true;
        
// TODO add your handling code here:
    }//GEN-LAST:event_lbl4MouseDragged

    private void lbltr4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltr4MouseEntered
if(t3){
    lbl3.setVisible(false);
    lbltr4.setIcon(new ImageIcon("src/Imagem/t4.jpg"));
    
}   
    
// TODO add your handling code here:
    }//GEN-LAST:event_lbltr4MouseEntered

    private void lbltr1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltr1MouseEntered

if(t1){
    lbl1.setVisible(false);
    lbltr1.setIcon(new ImageIcon("src/Imagem/t1.jpg"));
    
}        
// TODO add your handling code here:
    }//GEN-LAST:event_lbltr1MouseEntered

    private void lbltr2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltr2MouseEntered
      if(t4){
    lbl4.setVisible(false);
    lbltr2.setIcon(new ImageIcon("src/Imagem/t2.jpg"));
    
}   
        

// TODO add your handling code here:
    }//GEN-LAST:event_lbltr2MouseEntered

    private void lbltr3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltr3MouseEntered
if(t2){
    lbl2.setVisible(false);
    lbltr3.setIcon(new ImageIcon("src/Imagem/t3.jpg"));
    
}   
        
// TODO add your handling code here:
    }//GEN-LAST:event_lbltr3MouseEntered
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DFrmQuebraCabeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DFrmQuebraCabeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DFrmQuebraCabeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DFrmQuebraCabeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DFrmQuebraCabeca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbltr1;
    private javax.swing.JLabel lbltr2;
    private javax.swing.JLabel lbltr3;
    private javax.swing.JLabel lbltr4;
    // End of variables declaration//GEN-END:variables
}
