/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MenuSDI;

import javax.swing.JOptionPane;

/**
 *
 * @author lab
 */
public class frm_movimento extends javax.swing.JFrame {
boolean lata, rodo;
    /**
     * Creates new form frm_movimento
     */
    public frm_movimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbll = new javax.swing.JLabel();
        lblr = new javax.swing.JLabel();
        txtresposta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lab\\Desktop\\lata.jpg")); // NOI18N

        lbll.setText("Lata");
        lbll.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbllMouseDragged(evt);
            }
        });

        lblr.setText("Rodo");
        lblr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblrMouseDragged(evt);
            }
        });

        txtresposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtrespostaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtrespostaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbll, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblr, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtresposta, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbll)
                        .addGap(73, 73, 73)
                        .addComponent(lblr))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(txtresposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbllMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllMouseDragged
lbll.setLocation(lbll.getX() + evt.getX(), lbll.getY() + evt.getY());
lata = true;
rodo=false;
        
// TODO add your handling code here:
    }//GEN-LAST:event_lbllMouseDragged

    private void lblrMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrMouseDragged
lblr.setLocation(lblr.getX() + evt.getX(),lblr.getY() + evt.getY());
lata = false;
        rodo=true;
        // TODO add your handling code here:
    }//GEN-LAST:event_lblrMouseDragged

    private void txtrespostaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrespostaMouseEntered
if (lata)
{
    lbll.setVisible(false);
    txtresposta.setText("Lata");
    JOptionPane.showMessageDialog(null,"Parabéns");
    lata = false;
    
}
if(rodo){
      lblr.setVisible(false);
    rodo = false;
    JOptionPane.showMessageDialog(null,"Burrooo");
    
}


        
// TODO add your handling code here:
    }//GEN-LAST:event_txtrespostaMouseEntered

    private void txtrespostaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrespostaMouseExited

     lata = false;
 rodo=false;
 
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrespostaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_movimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_movimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_movimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_movimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_movimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbll;
    private javax.swing.JLabel lblr;
    private javax.swing.JTextField txtresposta;
    // End of variables declaration//GEN-END:variables
}
